package Groupproject;
import java.sql.*;

public class DBSetup {
    private static final String DB_URL = "jdbc:oracle:thin:@fsktmdbora.upm.edu.my:1521:fsktm";
    private static final String DB_USER = "E227105";
    private static final String DB_PASSWORD = "227105";

    public static void main(String[] args) {
        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
             Statement stmt = conn.createStatement()) {

            String[] tables = {"records_227105", "users_227105", "books_227105"};
            for (String t : tables) {
                try { stmt.executeUpdate("DROP TABLE " + t + " PURGE"); } catch (Exception e) {}
            }

            // 1. 书籍表：增加了 BORROWER_ID 字段
            stmt.executeUpdate("CREATE TABLE books_227105 (" +
                    "book_id VARCHAR2(20) PRIMARY KEY, " +
                    "title VARCHAR2(100), " +
                    "status VARCHAR2(20), " +
                    "borrower_id VARCHAR2(20)) STORAGE (INITIAL 16K)");

            // 2. 用户表
            stmt.executeUpdate("CREATE TABLE users_227105 (user_id VARCHAR2(20) PRIMARY KEY, name VARCHAR2(50), role VARCHAR2(20)) STORAGE (INITIAL 16K)");

            // 3. 记录表
            stmt.executeUpdate("CREATE TABLE records_227105 (record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "user_id VARCHAR2(20), book_id VARCHAR2(20), action VARCHAR2(20), action_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP) STORAGE (INITIAL 16K)");

            // 初始数据
            stmt.executeUpdate("INSERT INTO users_227105 VALUES ('ADMIN01', 'System Admin', 'ADMIN')");
            stmt.executeUpdate("INSERT INTO users_227105 VALUES ('U001', 'Student A', 'STUDENT')");
            stmt.executeUpdate("INSERT INTO books_227105 VALUES ('B001', 'Java Programming', 'Available', NULL)");

            System.out.println("数据库已重置！书籍表格现在包含 Borrower ID 列。");
        } catch (SQLException e) { e.printStackTrace(); }
    }
}